image: java:8

# Disable the Gradle daemon for Continuous Integration servers as correctness
# is usually a priority over speed in CI environments. Using a fresh
# runtime for each build is more reliable since the runtime is completely
# isolated from any previous builds.

# TODO: work out shadowjar nonsense
variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle

build:
  stage: build
  script: 
    - sed -i 's/IDE/RELEASE/g' src/main/java/me/rigamortis/seppuku/impl/fml/core/SeppukuClassTransformer.java
    - chmod +x gradlew
    - ./gradlew setupDecompWorkspace
    - ./gradlew build
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 month
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - build
      - .gradle
